"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 20:57:29.224177

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import fmaiily.db
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expiry', fmaiily.db.UTCDateTime(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('token_uri', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_refresh_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.Column('last_refresh_error', sa.Text(), nullable=True),
    sa.Column('daily_message_limit', sa.Integer(), nullable=False),
    sa.Column('daily_recipient_limit', sa.Integer(), nullable=False),
    sa.Column('soft_limit_ratio', sa.Float(), nullable=False),
    sa.Column('send_interval_seconds', sa.Float(), nullable=False),
    sa.Column('next_send_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_next_send_at'), ['next_send_at'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('allowed_accounts', sa.JSON(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('created_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.Column('last_used_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=True)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('account_hint', sa.String(length=320), nullable=True),
    sa.Column('created_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.Column('expires_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.Column('consumed_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('send_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_payload_enc', sa.Text(), nullable=True),
    sa.Column('payload_expires_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_scope', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.Column('lease_expires_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=64), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.Column('sent_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.Column('finished_at', fmaiily.db.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_scope', 'idempotency_key', name='uq_jobs_scope_idem')
    )
    with op.batch_alter_table('send_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_account_sent', ['account_id', 'sent_at'], unique=False)
        batch_op.create_index('ix_jobs_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_jobs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_jobs_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_jobs_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_jobs_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_jobs_status'), ['status'], unique=False)

    op.create_table('send_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', fmaiily.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['send_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_send_events_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_send_events_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_events_job_id'))
        batch_op.drop_index(batch_op.f('ix_send_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_send_events_account_id'))

    op.drop_table('send_events')
    with op.batch_alter_table('send_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_send_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_send_jobs_sent_at'))
        batch_op.drop_index(batch_op.f('ix_send_jobs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_send_jobs_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_send_jobs_account_id'))
        batch_op.drop_index('ix_jobs_account_status')
        batch_op.drop_index('ix_jobs_account_sent')

    op.drop_table('send_jobs')
    op.drop_table('oauth_states')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))

    op.drop_table('api_keys')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_next_send_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_email'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
