"""add request_hash to send_jobs

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 22:20:53.854193

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import fmaiily.db
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_jobs', schema=None) as batch_op:
        batch_op.drop_column('request_hash')

    # ### end Alembic commands ###
